apiVersion: v1
kind: Service
metadata:
    name: "myaksculsters008-be89"
    labels:
        app: "myaksculsters008-be89"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "myaksculsters008-be89"