apiVersion: v1
kind: Service
metadata:
    name: "myaks007-976a"
    labels:
        app: "myaks007-976a"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "myaks007-976a"