on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: sampconregistry001.azurecr.io
        username: ${{ secrets.acr_sampconregistry001_username }}
        password: ${{ secrets.acr_sampconregistry001_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t sampconregistry001.azurecr.io/myaks007:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push sampconregistry001.azurecr.io/myaks007:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks007_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaks007aa32 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaks007aa32`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaks007aa32
        container-registry-url: sampconregistry001.azurecr.io
        container-registry-username: ${{ secrets.acr_sampconregistry001_username }}
        container-registry-password: ${{ secrets.acr_sampconregistry001_password }}
        secret-name: myaks007dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaks007aa32
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          sampconregistry001.azurecr.io/myaks007:${{ github.sha }}
        imagepullsecrets: |
          myaks007dockerauth
